import os
import sys
from typing import List, Union

from rdkit import Chem
from rdkit.Chem import QED, Crippen
from rdkit import RDConfig

from rdkit.Chem import AllChem
from rdkit.DataStructs import TanimotoSimilarity

sys.path.append(os.path.join(RDConfig.RDContribDir, 'SA_Score'))
import sascorer
from rdkit import RDLogger

RDLogger.DisableLog('rdApp.*')


def calc_har(affinity_scores: List[float], threshold: float = -7.55) -> float:
    """
    计算高亲和力分子比例 (High Affinity Ratio, HAR)

    Args:
        affinity_scores: 对接打分值列表（Vina Score，通常为负值）
        threshold: 判断高亲和力的阈值

    Returns:
        HAR 值（0~1之间）
    """
    if not affinity_scores:
        return 0.0
    high_affinity_count = sum(score <= threshold for score in affinity_scores)
    return high_affinity_count / len(affinity_scores)

def calc_novelty(train_set: Union[str, List[str]], generated_molecules: List[str]) -> float:
    """
    Calculates the novelty score of the generated molecule list.
    the novelty score is the ratio between the amount of molecules that aren't in the train set
    and the size of the entire generate molecule list.

    |gen_molecules - train_set_molecules|
    ---------------------------
           |gen_molecules|

    Args:
        train_path:
            The data used to train the model with or a list of the loaded molecdules

        generated_molecules:
            List of molecuels that were generated by the model, molecules are in SMILES form.

    Returns:
        The novelty score of the generated set.
        novlty score ranges between 0 and 1.
    """
    new_molecules = set(generated_molecules) - set(train_set)
    new_molecules = len(new_molecules)

    novelty_score = new_molecules / len(generated_molecules)
    return novelty_score


# def calc_diversity(gen_molecules: List[str]) -> float:
#     """
#     Calculates the diversity of the generate molecule list.
#     The diversity is the number of unique molecules in the generated list.
#
#     |unqiue(gen_molecules)|
#     ------------------
#         |gen_molecules|
#
#     Args:
#         gen_molecules:
#             List of molecules that werte generated by the model, molecules are in SMILES form.
#
#     Returns:
#         The diversity score of the generated set.
#         diversity score ranges between 0 and 1.
#     """
#     return len(set(gen_molecules)) / len(gen_molecules)

def calc_diversity(gen_molecules: List[str]) -> float:
    """
    Calculate true chemical diversity based on Tanimoto similarity.
    Diversity = 1 - average pairwise Tanimoto similarity.
    Higher value (closer to 1) means more diverse.
    """
    mols = [Chem.MolFromSmiles(smi) for smi in gen_molecules]
    mols = [mol for mol in mols if mol is not None]  # Filter invalid molecules

    if len(mols) < 2:
        return 0.0  # Not enough molecules to compare

    # Generate Morgan fingerprints (radius=2, 1024 bits)
    fps = [AllChem.GetMorganFingerprintAsBitVect(mol, 2, nBits=1024) for mol in mols]

    total_similarity = 0.0
    count = 0

    # Calculate all pairwise similarities
    for i in range(len(fps)):
        for j in range(i + 1, len(fps)):
            total_similarity += TanimotoSimilarity(fps[i], fps[j])
            count += 1

    avg_similarity = total_similarity / count if count > 0 else 0.0
    diversity = 1 - avg_similarity

    return diversity


def calc_logp(mol: Chem.rdchem.Mol) -> float:
    """
    Calculates the logP for a given molecule.

    Args:
        mol:
            An rdkit molecule object.

    Returns:
        the molecule log p which is his the log ratio between
        water solubility and octanol solubility.
    """
    log_p = Crippen.MolLogP(mol)

    return log_p


def calc_qed(mol: Chem.rdchem.Mol) -> float:
    """
    Calculates the quantitative estimation of drug-likeness of a given molecule.

    Args:
        mol:
            An rdkit molecule object.

    Returns:
        the molecule qed value which estimate how much this molecule
        resemebles a drug.
    """
    qed = QED.qed(mol)

    return qed


def calc_sas(mol: Chem.rdchem.Mol) -> float:
    """
    Calculates the Synthetic Accessiblity Score (SAS) of a drug-like molecule
    based on the molecular compelxity and fragment contribution.

    code taken from: https://github.com/rdkit/rdkit/blob/master/Contrib/SA_Score/sascorer.py

    Args:
        A rdkit molecule object.

    Returns:
        The SAS score of a given molecule.

    Raises

    """
    # try:
    sascore = sascorer.calculateScore(mol)
    return sascore
    # except Exception as e:
    #     print(f"Error calculating SA score: {e}")
    #     return None


def calc_valid_molecules(molecules: List[str]) -> float:
    valid_molecules = [mol for mol in molecules if Chem.MolFromSmiles(mol) is not None]

    return len(valid_molecules) / len(molecules)

def Estimate_logP(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return 0
    else:
        try:
            return  Chem.Crippen.MolLogP(mol)
        except:
            return 0


def Estimate_QED(smiles):

    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return 0
    else:
        try:
            return QED.qed(mol)
        except:
            return 0


def Estimate_SA(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return 0
    else:
        return sascorer.calculateScore(mol)
